[package]
name = "wordmap"
version = "0.1.0"
edition = "2021"

[dependencies]
getrandom = "0.2.8"

[dev-dependencies]
expect-test = "1.4.0"
fxhash = "0.2.1"
hashbrown = { version = "0.13.2", features = [ "ahash" ] }
