[package]
name = "intmap"
version = "0.1.0"
edition = "2021"

[dependencies]
getrandom = "0.2.8"

[dev-dependencies]
expect-test = "1.4.0"
# ahash = { version = "0.8.2", features = [ "std" ] }
# fxhash = { version = "0.2.1" }

# [[bench]]
# name = "bench"
# harness = false
